# Generated by Django 5.1.2 on 2024-10-26 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_emailverificationcode_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
