# Generated by Django 5.1.2 on 2024-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
