# Generated by Django 5.1.2 on 2024-10-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile.jpg', null=True, upload_to='avatars/'),
        ),
    ]
